# Gradle 全局配置
org.gradle.jvmargs=-Xmx4g -XX:+UseParallelGC -Dfile.encoding=UTF-8
org.gradle.parallel=true
org.gradle.caching=true
org.gradle.configuration-cache=true

# AndroidX
android.useAndroidX=true
# 仅生成用到的 BuildConfig 字段，缩短构建时间
android.nonTransitiveRClass=true

# Kotlin 代码风格
kotlin.code.style=official
